name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, pi]
    steps:
      - name: Pull latest
        working-directory: /home/orrinmanning/orrin-dev
        run: git pull origin master

      - name: Rebuild and restart
        working-directory: /home/orrinmanning/orrin-dev
        run: docker compose --profile prod up -d --build
